@description('Where the resources go.')
param location string

@description('Suffix that makes globally-unique names unique.')
param suffix string

@description('Tags applied to everything in this module.')
param tags object

@description('Object id allowed to write secrets. The deploying principal.')
param administratorObjectId string

@description('The JWT signing key. Generated by the caller and never committed.')
@secure()
param jwtSigningKey string

@description('Principal id of the workload identity that reads the signing key.')
param workloadPrincipalId string

// Vault names are global and capped at 24 characters, so this one is abbreviated.
resource vault 'Microsoft.KeyVault/vaults@2024-11-01' = {
  name: 'kv-sp-${suffix}'
  location: location
  tags: tags
  properties: {
    sku: { family: 'A', name: 'standard' }
    tenantId: subscription().tenantId

    // RBAC rather than access policies. Policies are per-vault ACLs that nothing else in
    // Azure understands; RBAC is the same model as every other resource here, and it is what
    // lets a role assignment be scoped to one secret rather than to the whole vault.
    enableRbacAuthorization: true

    enableSoftDelete: true
    softDeleteRetentionInDays: 7

    // Purge protection off, deliberately. With it on the vault's name stays reserved for the
    // whole retention period, and a teardown-and-rebuild — which is the normal lifecycle of
    // this environment — fails on a name-in-use error that points nowhere near the cause.
    // P6 learned this and wrote it down; the same reasoning applies here.
    enablePurgeProtection: null

    publicNetworkAccess: 'Enabled'
    networkAcls: {
      defaultAction: 'Allow'
      bypass: 'AzureServices'
    }
  }
}

// The deploying principal needs to write the secret it is about to create. Vault RBAC is not
// implied by Contributor on the resource group: Contributor can create a vault and cannot
// read or write anything inside it, which is the distinction that catches everybody once.
resource administratorIsSecretsOfficer 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: vault
  name: guid(vault.id, administratorObjectId, 'Key Vault Secrets Officer')
  properties: {
    principalId: administratorObjectId
    // Key Vault Secrets Officer
    roleDefinitionId: subscriptionResourceId(
      'Microsoft.Authorization/roleDefinitions',
      'b86a8fe4-44ce-4948-aee5-eccb2c155cd7'
    )
  }
}

// The only secret in the deployment. The database needs none: SQL is Entra-only and the
// identities connecting supply their own credential, so there is no connection string here
// with a password in it.
resource signingKey 'Microsoft.KeyVault/vaults/secrets@2024-11-01' = {
  parent: vault
  name: 'jwt-signing-key'
  properties: {
    value: jwtSigningKey
    contentType: 'text/plain'
  }
  dependsOn: [administratorIsSecretsOfficer]
}

// Read this vault's secrets. Not write, not manage, not list. Declared here for the same
// reason as the storage grant: a role assignment's scope must be computable at the start of
// the deployment, and a module output is not.
resource canReadSecrets 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: vault
  name: guid(vault.id, workloadPrincipalId, 'Key Vault Secrets User')
  properties: {
    principalId: workloadPrincipalId
    principalType: 'ServicePrincipal'
    roleDefinitionId: subscriptionResourceId(
      'Microsoft.Authorization/roleDefinitions',
      '4633458b-17de-408a-b874-0445c86b69e6'
    )
  }
}

output vaultName string = vault.name
output vaultUri string = vault.properties.vaultUri
output vaultId string = vault.id
output signingKeySecretUri string = signingKey.properties.secretUri
